### ISSUE TITLE
udp cant use

### ISSUE THREAD

**Issue by keainala** [Mun1z/KingNetwork#6]

**Comment by MUN1Z** [comment]
You can add more descriptions @keainala ?

![image](https://user-images.githubusercontent.com/17263249/98171356-5e5a3b00-1ece-11eb-929f-f4bbc450bf61.png)

The simple example on repository is working...

**Comment by keainala** [comment]
127.0.0.1  useful， use ip like 192.168.1.6  it cant use

**Comment by MUN1Z** [comment]
Interesting @keainala , I'll take a look in a moment and give you feedback, thanks.

**Comment by keainala** [comment]
@Mun1z  thank godness，i think u understand my word

**Comment by keainala** [comment]
i find out the place where the code run error ->  udp client cant bind

**Comment by MUN1Z** [comment]
@keainala sorry for delay, correction for this issue in last commit: https://github.com/Mun1z/KingNetwork/commit/a36aec417b4eafe6b3a444e300a29e9956f14dab
